development:
  adapter: postgresql
  database: pomarity_development
  pool: 5
  host: localhost
  username: mesitis
  password: mesitis123

test:
  adapter: postgresql
  database: pomarity_test
  pool: 5
  host: localhost
  username: mesitis
  password: mesitis123